### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by avenmia**
*  Creates a simple login page flow
*  Adds husky
*  Adds prettier
*  Adds lint-staged

### CODE REVIEW

**Comment by kmal808** [comment]
Output upon commit # 17ef79a
``` json
["INFO" - 7:53:54 AM] Formatting file:///c%3A/Users/Kmalley/repos/go-or-no/src/pages/index.astro
["INFO" - 7:53:54 AM] Using ignore file (if present) at c:\Users\Kmalley\repos\go-or-no\.prettierignore
["INFO" - 7:53:54 AM] File Info:
{
  "ignored": false,
  "inferredParser": "astro"
}
["INFO" - 7:53:54 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 7:53:54 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": true,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": true,
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\Kmalley\\repos\\go-or-no\\src\\pages\\index.astro",
  "parser": "astro"
}
["INFO" - 7:53:54 AM] Formatting completed in 21ms.``` 
File was formatted with my Prettier configuration.

**Comment by avenmia** [comment]
Let's define a prettier config for the repo then, it was probably using my default one too.

Rules I prefer are:
*  2 spaces
*  double quotes
*  semi colons on 

Let me know if you're passionately against any of those

**Comment by kmal808** [comment]
> Let's define a prettier config for the repo then, it was probably using my default one too.
> 
> Rules I prefer are:
> 
> * 2 spaces
> * double quotes
> * semi colons on
> 
> Let me know if you're passionately against any of those

Passionately against any, no not really. 

Either way, I can still yolo with single quotes and no semi colons and let the formatter do its magic. 

This would be my current config with the project preferences adjusted.

```
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": true,
  "vueIndentScriptAndStyle": false,
  "parser": "astro"
}
```

Or go "minimalist" 

```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false
}
```

Can drop one of those in the `prettierrc.json` yeah?
Thoughts?
Thoughts on thoughts?

**Comment by avenmia** [comment]
I like the minimalist version and adding to it if we need to 👍

**Comment by kmal808** [comment]
Pre-commit hook verified as working 192e9ac

```
["INFO" - 6:56:09 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 6:56:09 AM] Prettier Options:
{
  "filepath": "c:\\Users\\Kmalley\\repos\\go-or-no\\src\\pages\\home.astro",
  "parser": "astro",
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false
}
["INFO" - 6:56:09 AM] Formatting completed in 377ms.
```

**Pull request merged**
